kind: Deployment
apiVersion: apps/v1
metadata:
  name: meta-be
  namespace: pixel
  selfLink: /apis/apps/v1/namespaces/pixel/deployments/meta-be
  uid: 3a3a8c01-c825-4766-a8ef-6fc0eed4b19a
  resourceVersion: '23864200'
  generation: 1
  creationTimestamp: '2022-12-05T12:08:41Z'
  labels:
    k8s-app: meta-be
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"9"},"creationTimestamp":"2022-12-05T03:01:35Z","generation":31,"labels":{"k8s-app":"meta-be"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:k8s-app":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{"f:matchLabels":{".":{},"f:k8s-app":{}}},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/restartedAt":{}},"f:labels":{".":{},"f:k8s-app":{}},"f:name":{}},"f:spec":{"f:containers":{"k:{\"name\":\"git-repo-syncer\"}":{".":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/app\"}":{".":{},"f:mountPath":{},"f:name":{}}}},"k:{\"name\":\"meta-be\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:securityContext":{".":{},"f:privileged":{}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/mnt/nfs\"}":{".":{},"f:mountPath":{},"f:name":{}},"k:{\"mountPath\":\"/workspace\"}":{".":{},"f:mountPath":{},"f:name":{}}}}},"f:dnsPolicy":{},"f:imagePullSecrets":{".":{},"k:{\"name\":\"git-gogs\"}":{".":{},"f:name":{}}},"f:initContainers":{".":{},"k:{\"name\":\"git-clone-metabe\"}":{".":{},"f:command":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/app\"}":{".":{},"f:mountPath":{},"f:name":{}}}}},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{},"f:volumes":{".":{},"k:{\"name\":\"git-metabe\"}":{".":{},"f:emptyDir":{},"f:name":{}},"k:{\"name\":\"metaverse\"}":{".":{},"f:name":{},"f:persistentVolumeClaim":{".":{},"f:claimName":{}}}}}}}},"manager":"dashboard","operation":"Update","time":"2022-12-05T07:31:47Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:deployment.kubernetes.io/revision":{}}},"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:updatedReplicas":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2022-12-05T11:56:51Z"}],"name":"meta-be","namespace":"pixel","resourceVersion":"23760708","selfLink":"/apis/apps/v1/namespaces/pixel/deployments/meta-be","uid":"416814ef-7339-43f4-8630-93e5ad5e050e"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"k8s-app":"meta-be"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2022-12-05T03:30:18Z"},"creationTimestamp":null,"labels":{"k8s-app":"meta-be"},"name":"meta-be"},"spec":{"containers":[{"command":["/bin/bash","-ec","[[
      -f \"/opt/bitnami/scripts/git/entrypoint.sh\" ]] \u0026\u0026 source
      \"/opt/bitnami/scripts/git/entrypoint.sh\"\nwhile true; do\n    cd /app
      \u0026\u0026 git pull origin main\n    sleep
      5\ndone\n"],"image":"docker.io/bitnami/git:2.37.3-debian-11-r0","imagePullPolicy":"IfNotPresent","name":"git-repo-syncer","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/app","name":"git-metabe"}]},{"image":"SXKJ:32775/meta_be","imagePullPolicy":"Always","name":"meta-be","resources":{},"securityContext":{"privileged":false},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/mnt/nfs","name":"metaverse"},{"mountPath":"/workspace","name":"git-metabe"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"git-gogs"}],"initContainers":[{"command":["/bin/bash","-ec","[[
      -f \"/opt/bitnami/scripts/git/entrypoint.sh\" ]] \u0026\u0026 source
      \"/opt/bitnami/scripts/git/entrypoint.sh\"\ngit clone
      http://gogs.soaringnova.com/sxwl_DL/meta_be.git --branch main
      /app\n"],"image":"docker.io/bitnami/git:2.37.3-debian-11-r0","imagePullPolicy":"IfNotPresent","name":"git-clone-metabe","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/app","name":"git-metabe"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"metaverse","persistentVolumeClaim":{"claimName":"metaverse-pvc"}},{"emptyDir":{},"name":"git-metabe"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-12-05T03:01:35Z","lastUpdateTime":"2022-12-05T07:32:42Z","message":"ReplicaSet
      \"meta-be-77fbcbbdbb\" has successfully
      progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2022-12-05T11:56:51Z","lastUpdateTime":"2022-12-05T11:56:51Z","message":"Deployment
      has minimum
      availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":31,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-05T12:08:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:k8s-app: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector:
            f:matchLabels:
              .: {}
              f:k8s-app: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/restartedAt: {}
              f:labels:
                .: {}
                f:k8s-app: {}
              f:name: {}
            f:spec:
              f:containers:
                k:{"name":"git-repo-syncer"}:
                  .: {}
                  f:command: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/app"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                k:{"name":"meta-be"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:privileged: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/mnt/nfs"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/workspace"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:imagePullSecrets:
                .: {}
                k:{"name":"git-gogs"}:
                  .: {}
                  f:name: {}
              f:initContainers:
                .: {}
                k:{"name":"git-clone-metabe"}:
                  .: {}
                  f:command: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/app"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"git-metabe"}:
                  .: {}
                  f:emptyDir: {}
                  f:name: {}
                k:{"name":"metaverse"}:
                  .: {}
                  f:name: {}
                  f:persistentVolumeClaim:
                    .: {}
                    f:claimName: {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-12-05T20:45:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: meta-be
  template:
    metadata:
      name: meta-be
      creationTimestamp: null
      labels:
        k8s-app: meta-be
      annotations:
        kubectl.kubernetes.io/restartedAt: '2022-12-05T03:30:18Z'
    spec:
      volumes:
        - name: metaverse
          persistentVolumeClaim:
            claimName: metaverse-pvc
        - name: git-metabe
          emptyDir: {}
      initContainers:
        - name: git-clone-metabe
          image: docker.io/bitnami/git:2.37.3-debian-11-r0
          command:
            - /bin/bash
            - '-ec'
            - >
              [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source
              "/opt/bitnami/scripts/git/entrypoint.sh"

              git clone http://gogs.soaringnova.com/sxwl_DL/meta_be.git --branch
              main /app
          resources: {}
          volumeMounts:
            - name: git-metabe
              mountPath: /app
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: git-repo-syncer
          image: docker.io/bitnami/git:2.37.3-debian-11-r0
          command:
            - /bin/bash
            - '-ec'
            - >
              [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source
              "/opt/bitnami/scripts/git/entrypoint.sh"

              while true; do
                  cd /app && git pull origin main
                  sleep 5
              done
          resources: {}
          volumeMounts:
            - name: git-metabe
              mountPath: /app
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: meta-be
          image: SXKJ:32775/meta_be
          resources: {}
          volumeMounts:
            - name: metaverse
              mountPath: /mnt/nfs
            - name: git-metabe
              mountPath: /workspace
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: git-gogs
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-12-05T12:09:23Z'
      lastTransitionTime: '2022-12-05T12:08:42Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "meta-be-77fbcbbdbb" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-12-05T20:45:37Z'
      lastTransitionTime: '2022-12-05T20:45:37Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
