kind: Deployment
apiVersion: apps/v1
metadata:
  name: meta-be
  namespace: pixel
  labels:
    k8s-app: meta-be
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: meta-be
  template:
    metadata:
      name: meta-be
      creationTimestamp: null
      labels:
        k8s-app: meta-be
    spec:
      volumes:
        - name: metaverse
          persistentVolumeClaim:
            claimName: metaverse-pvc
        - name: git-metabe
          emptyDir: {}
      initContainers:
        - name: git-clone-metabe
          image: docker.io/bitnami/git:2.37.3-debian-11-r0
          command:
            - /bin/bash
            - '-ec'
            - >
              [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source
              "/opt/bitnami/scripts/git/entrypoint.sh"

              git clone http://gogs.soaringnova.com/sxwl_DL/meta_be.git --branch
              main /app
          resources: {}
          volumeMounts:
            - name: git-metabe
              mountPath: /app
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: git-repo-syncer
          image: docker.io/bitnami/git:2.37.3-debian-11-r0
          command:
            - /bin/bash
            - '-ec'
            - >
              [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source
              "/opt/bitnami/scripts/git/entrypoint.sh"

              while true; do
                  cd /app && git pull origin main
                  sleep 60
              done
          resources: {}
          volumeMounts:
            - name: git-metabe
              mountPath: /app
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: meta-be
          image: SXKJ:32775/meta_be
          resources: {}
          volumeMounts:
            - name: metaverse
              mountPath: /mnt/nfs
            - name: git-metabe
              mountPath: /workspace
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: git-gogs
