version: '2'
services:
  meta_be:
    hostname: meta_be
    container_name: meta_be
    restart: always
    image: SXKJ:32775/meta_be:latest
    privileged: true
    ipc: host
    tty: true
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./be.conf:/etc/supervisor/conf.d/be.conf
    ports:
      - '20080:8080'

