pipeline {
  agent {
    kubernetes {
      yamlFile 'deploy/sxtest/KubernetesPod.yaml'
      retries 2
    }
  }
  stages {
    stage('构建镜像') {
      steps {
        container('docker') {
          echo "构建 Docker 镜像阶段"
          sh 'docker build  -t SXKJ:32775/meta-app:latest --output type=docker .'
          echo "build success"
        }
        container('kubectl') {
          sh 'kubectl version'
        }
      }
    }
    stage('镜像推送') {
      steps {
        container('docker') {
          echo "Push Docker 镜像阶段"
          sh 'docker push SXKJ:32775/meta-app:latest '
          echo "Push image success"
        }
      }
    }
  }
}