def label = "slave-${UUID.randomUUID().toString()}"

podTemplate(cloud: 'kubernetes', namespace:'devops',label: label, serviceAccount: 'jenkins',containers: [
  containerTemplate(name: 'docker', image: 'docker:latest', command: 'cat', ttyEnabled: true),
  containerTemplate(name: 'kubectl', image: 'cnych/kubectl', command: 'cat', ttyEnabled: true)
],volumes: [
  hostPathVolume(mountPath: '/home/jenkins/.kube', hostPath: '/root/.kube'),
  hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  hostPathVolume(mountPath: '/etc/docker/daemon.json', hostPath: '/etc/docker/daemon.json')
], yaml: """
spec:
  nodeSelector:
    kubernetes.io/hostname: h249
  hostalias:
  - ip: 192.168.199.31
    hostnames:
    - "SXKJ"
"""
) {
  node(label) {
    stage('构建 Docker 镜像') {
      git url: ' http://gogs.soaringnova.com/sxwl_DL/meta_be.git', branch: 'master'
      container('docker') {
        echo "构建 Docker 镜像阶段"
        // sh "echo '192.168.199.31 SXKJ' >> /etc/hosts"
        sh "docker build  -t SXKJ:32775/meta-app:latest --output type=docker ."
        echo "build success"
      }
    }
    stage('Docker Push 镜像') {
        container('docker') {
          sh "docker push SXKJ:32775/meta-app:latest"
          echo "Push success"
        }
    }
    stage('运行 Kubectl') {
      container('kubectl') {
        echo "查看 K8S 集群 Pod 列表"
        sh "kubectl rollout restart deployments/app-be  -n meta-demo"
      }
    }
  }
}