// pipeline {
//   agent {
//     kubernetes {
//       yaml '''
//         apiVersion: v1
//         kind: Pod
//         spec:
//           containers:
//           - name: maven
//             image: maven:alpine
//             command:
//             - cat
//             tty: true
//       '''
//     }
//   }
//   stages {
// //     stage('Clone') {
// //       steps {
// //         checkout([$class: 'GitSCM', branches: [[name: '${tag}']], extensions: [], userRemoteConfigs: [[credentialsId: 'gogs', url: 'http://gogs.soaringnova.com/sxwl_DL/meta_be.git']]])
// //       }
// //     }
//     stage('构建镜像') {
//         steps {
//             container('maven') {
//                 sh 'maven -version'
//             }
//         }
//     }
//   }
// }
//
//
//

podTemplate(
    label: "kubernetes",
    containers: [
        containerTemplate(name: "maven", image: "maven:alpine", ttyEnabled: true, command: "cat")
    ]
) {
    node("kubernetes") {
        container("maven") {
            stage("build") {
                sh "mvn --version"
            }
        }
    }
}