services:
  
  # The WebRTC TURN server (note that you will need TCP and UDP ports 3478 and 49152-65535 exposed for TURN relaying to function correctly)
  turnserver:
    image: "SXKJ:32775/coturn:4.5.2"
    init: true
    network_mode: "host"
    command: [ "-a", "-v", "-n", "-u", "user:password", "-p", "3478", "-r", "default-realm", "--no-dtls", "--no-tls" ]
  
  # The Cirrus signalling server
  signalling:
    image: "SXKJ:32775/pixel-streaming-signalling-server:${UNREAL_ENGINE_RELEASE}"
    init: true
    network_mode: "host"
    command:
      - "--publicIp=${PUBLIC_IP}"
      - "--HttpPort=81"
      - >-
        --peerConnectionOptions={
        
            "iceServers":[
              {
                "urls": ["stun:stun.l.google.com:19302"]
              },
              {
                "urls": ["turn:${PUBLIC_IP}:3478"],
                "name": "user",
                "credential": "password"
              }
            ]
            ${EXTRA_PEERCONNECTION_OPTIONS}
          }
    depends_on:
      - turnserver



  project:
    image: SXKJ:32775/pixel-streaming-example:project #"SXKJ:32775/unreal-engine:runtime-pixel-streaming"
#    init: true
    network_mode: "host"
#    tty: true
#    volumes:
#      - /home/sxkj/metaverse_linux_package/LinuxNoEditor:/workspace
#    runtime: nvidia
#    command: ["/workspace/yanshi_demo.sh", "-RenderOffscreen", "-Windowed", "-ForceRes", "-ResX=1920", "-ResY=1080", "-PixelStreamingIP=127.0.0.1","-PixelStreamingPort=8888",]
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              capabilities: [ gpu ]
#              count: 1
    depends_on:
      - signalling

#   The Pixel Streaming demo project
#  project:
#    image: "pixel-streaming-example/project"
#    build:
#      context: project
#      args:
#        RELEASE: "${UNREAL_ENGINE_RELEASE}"
#    network_mode: "host"
#
#    depends_on:
#      - signalling
#
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              capabilities: [ gpu ]
#              count: 1


